apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-project-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: final-project
  template:
    metadata:
      labels:
        app: final-project
    spec:
      containers:
        - name: final-project
          image: docker.io/panrosk/cicdfinalgo:f64334f8e4677f5b2d39bd7329b41b63f41cd51f
          imagePullPolicy: Always
          ports:
            - containerPort: 80
