apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-project-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: final-project
  template:
    metadata:
      labels:
        app: final-project
    spec:
      containers:
        - name: final-project
          image: docker.io/panrosk/cicdfinalgo:eaeba27729fa34a329e9947f5575d705fbd04ece
          imagePullPolicy: Always
          ports:
            - containerPort: 80
