apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-project-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: final-project
  template:
    metadata:
      labels:
        app: final-project
    spec:
      containers:
        - name: final-project
          image: docker.io/panrosk/cicdfinalgo:42553d68b53157a0eb807e60f997c6a3b71ad2d1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
