apiVersion: v1
kind: Service
metadata:
  name: final-project-service
  labels:
    app: final-project
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  type: NodePort
  selector:
    app: final-project
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30008
