apiVersion: v1
kind: Service
metadata:
  name: final-project-service
spec:
  type: NodePort
  selector:
    app: final-project
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 3000
